default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: 127.0.0.1
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: leiloeiro_development

test:
  <<: *default
  database: leiloeiro_test

production:
  <<: *default
  database: leiloeiro_production
  username: leiloeiro
  password: <%= ENV['LEILOEIRO_DATABASE_PASSWORD'] %>
